### ISSUE TITLE
Consider using a database to store all calendar information

### ISSUE THREAD

**Issue by MrClement** [dchao19/KentAPIs#3]
Will be much faster to respond to requests - no need to make requests to external resources. Also will will allow us to add special schedule days / tweak the schedule via POST

**Comment by dchao19** [comment]
I agree - remote api procedure in this context probably isn't the way to go.

I'm thinking MongoDB or another non relational/nosql database. I can setup an instance on azure if you'd like.

**Comment by MrClement** [comment]
I am happy to do whatever. We could also use sqlite to be able to just work from Github during the early stages of development. Is there any particular reason to use Azure?

**Comment by MrClement** [comment]
Also: http://unqlite.org/

**Comment by dchao19** [comment]
I'd be down - don't got any idea on how to use it though.

I was thinking: https://github.com/hideo55/node-unqlite

**Comment by MrClement** [comment]
In progress. See 9df3ff9d759efd688cab18f7caaf2ffa16411698

**Comment by MrClement** [comment]
Done. Using MongoDB.
